name: 'Test Windows'

on:
  - pull_request

jobs:
  test:
    name: 'Test'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: 'Build action'
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: 'Build action'
        run: |
          yarn run build
      - name: 'Test action'
        uses: ./
        with:
          lokalise-version: 'latest'
      - name: 'Test lokalise'
        run: 'lokalise2 --version'
